services:
  app:
    container_name: gogo_app
    image: gogo
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - DB_ENDPOINT=gogo_db:2379
    ports:
      - "8080:8080"
    volumes:
      - gogo_app_vol:/app
    depends_on:
      - etcd
  etcd:
    container_name: gogo_db
    image: bitnami/etcd:3.4.18
    ports:
      - "2379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - gogo_db_vol:/data
 
volumes:
  gogo_app_vol:
    driver: local
  gogo_db_vol:
    driver: local