# syntax=docker/dockerfile:1

FROM golang:1.17-alpine

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
COPY project ./project

RUN go mod download
RUN go build project/server/main.go

EXPOSE 8080

CMD [ "./main" ];